"""Language profile registry for built-in pipeline defaults."""

from scripts.language_profiles.italian import (
    DEFAULT_GLOSSARY_HEADING,
    DEFAULT_GLOSSARY_RULES,
    DEFAULT_LEARNER_NATIVE_LANGUAGE,
    DEFAULT_LEGACY_GLOSSARY_HEADINGS,
    DEFAULT_LOCALE,
    DEFAULT_PROMPT_PACK,
    DEFAULT_SITE_NAME,
    DEFAULT_SPACY_MODEL,
    DEFAULT_TARGET_LANGUAGE,
    DEFAULT_TARGET_LANGUAGE_CODE,
)

SUPPORTED_GLOSSARY_RULES = {DEFAULT_GLOSSARY_RULES}
SUPPORTED_PROMPT_PACKS = {DEFAULT_PROMPT_PACK}

__all__ = [
    "DEFAULT_GLOSSARY_HEADING",
    "DEFAULT_GLOSSARY_RULES",
    "DEFAULT_LEARNER_NATIVE_LANGUAGE",
    "DEFAULT_LEGACY_GLOSSARY_HEADINGS",
    "DEFAULT_LOCALE",
    "DEFAULT_PROMPT_PACK",
    "DEFAULT_SITE_NAME",
    "DEFAULT_SPACY_MODEL",
    "DEFAULT_TARGET_LANGUAGE",
    "DEFAULT_TARGET_LANGUAGE_CODE",
    "SUPPORTED_GLOSSARY_RULES",
    "SUPPORTED_PROMPT_PACKS",
]
